---
title: "Tidying Data in R"
author: "Vibhor Agarwal"
date: "August 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
```

Calling a masked function

packageName::functionName

exampele
stats::filter()

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"), stringsAsFactors = FALSE)
head(catch_df)

```
```{r}
catch_df <- catch_df %>% 
    select(-All, -notesRegCode) 


```
Move from wide to long fromat (using gather) and rename the catch column to reflect units

```{r}
catch_df <- catch_df %>% 
  gather(key = "species", value = "catch", -Region, -Year)

unique(catch_df$species)
```

```{r}
catch_df <- catch_df %>% 
  rename(catch_thousands = catch)

head(catch_df)

```

Reverse of a gather is spread

Rename a column

```{r}
catch_integers <- as.integer(catch_df$catch_thousands)
i <- which(is.na(catch_integers) == T)
catch_df$catch_thousands[i]
```

1) turn "I" into 1 in catych thousands column
2) coece catch_thoussnds into integer type
3) convert catch_thousands to catch

```{r}
catch_df <- catch_df %>% 
  mutate(catch_thousands = ifelse(catch_thousands == "I",1, catch_thousands)) %>% 
  mutate(catch_thousands = as.integer(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000)
  
tail(catch_df)

```





